# Generated by Django 4.2.16 on 2024-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_like_users_usermovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=50)),
            ],
        ),
    ]
