# Generated by Django 4.2.16 on 2024-11-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
