# Generated by Django 4.2.16 on 2024-11-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_article_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
