# Generated by Django 4.2.16 on 2024-11-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_user_id_article_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
